### ISSUE TITLE
Catalyst School Meeting : 22th July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [The-Catalyst-School/The-Catalyst-School-Co-Ordination#11]
### Attendees
Kertsin
Raz
@Seomon4u - Simon 
 Felix
@whitevo - Tevo
@stephen-rowan - Stephen

## Minutes

https://docs.google.com/document/d/1iNt6ktI4tbzIhFG47GE5MU2Yyj5kC32884EI6LXBDXU/edit

## Video

https://drive.google.com/drive/folders/1IgLEagqYwEKPeQmcSydzgy5keuZ58R_e?usp=sharing

## Actions

MicroTask Catalyst School Workshop - 28th July 2021 - https://github.com/The-Catalyst-School/The-Catalyst-School-Co-Ordination/issues/12

**Comment by whitevo** [comment]
For minutes makes more sense to show Miro? https://miro.com/app/board/o9J_l8GW3mI=/?moveToWidget=3074457361171023249&cot=10

**Comment by stephen-rowan** [comment]
And a screenshot of the Miro (so it is archived here)
![2021-07-23](https://user-images.githubusercontent.com/25156451/126772248-47ae865e-e89e-43f7-bad3-8cecb5ae078f.png)
